/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_HelloJNI */

#ifndef _Included_com_example_demo_HelloJNI
#define _Included_com_example_demo_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_HelloJNI
 * Method:    sumMatrix
 * Signature: ([[C)I
 */
JNIEXPORT jint JNICALL Java_com_example_demo_HelloJNI_sumMatrix
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
